### ISSUE TITLE
Can't read FTB Quests NBT

### ISSUE THREAD

**Issue by AliceDTRH** [vberlier/nbtlib#185]
Error:
```shell
Traceback (most recent call last):
  File "/home/alice/bin/nbt", line 8, in <module>
    sys.exit(main())
    │        └ <function main at 0x7f05b71c3250>
    └ <module 'sys' (built-in)>
  File "/home/alice/.local/lib/python3.10/site-packages/nbtlib/cli.py", line 57, in main
    for tag in read(
  File "/home/alice/.local/lib/python3.10/site-packages/nbtlib/cli.py", line 79, in read
    nbt_file = parse_nbt(f.read())
               │         └ <_io.TextIOWrapper name="/home/alice/.local/share/multimc/instances/Alice's Modpack/.minecraft/local/ftbquests/saved/2022-08-08-...
               └ <function parse_nbt at 0x7f05b735caf0>
  File "/home/alice/.local/lib/python3.10/site-packages/nbtlib/literal/parser.py", line 105, in parse_nbt
    tag = parser.parse()
          └ <nbtlib.literal.parser.Parser object at 0x7f05b71d59f0>
  File "/home/alice/.local/lib/python3.10/site-packages/nbtlib/literal/parser.py", line 167, in parse
    return handler()
           └ <bound method Parser.parse_compound of <nbtlib.literal.parser.Parser object at 0x7f05b71d59f0>>
  File "/home/alice/.local/lib/python3.10/site-packages/nbtlib/literal/parser.py", line 213, in parse_compound
    for token in self.collect_tokens_until("CLOSE_COMPOUND"):
  File "/home/alice/.local/lib/python3.10/site-packages/nbtlib/literal/parser.py", line 206, in collect_tokens_until
    raise self.error(f"Expected comma but got {self.current_token.value!r}")
          │                                    └ <nbtlib.literal.parser.Parser object at 0x7f05b71d59f0>
          └ <nbtlib.literal.parser.Parser object at 0x7f05b71d59f0>
nbtlib.literal.parser.InvalidLiteral: Expected comma but got 'default_reward_team' at position 16
```
Command used: ``nbt -s data.snbt``
File contents:
```
{
	version: 13
	default_reward_team: false
	default_consume_items: false
	default_autoclaim_rewards: "disabled"
	default_quest_shape: "circle"
	default_quest_disable_jei: false
	emergency_items_cooldown: 300
	drop_loot_crates: false
	loot_crate_no_drop: {
		passive: 4000
		monster: 600
		boss: 0
	}
	disable_gui: false
	grid_scale: 0.5d
	pause_game: false
	lock_message: ""
}
```

I believe the issue may be that there's no commas? Is there a way to convert it anyway?
FTB Quests decided to store all their data in files like these and it would be useful if I could automate editing some of these.

**Comment by vberlier** [comment]
Hmm this isn't directly supported by `nbtlib` but you can extend the parser to let it continue when a comma would normally be expected.

```py
import nbtlib

class RelaxedParser(nbtlib.Parser):
    def collect_tokens_until(self, token_type):
        while True:
            try:
                yield from super().collect_tokens_until(token_type)
                return
            except nbtlib.InvalidLiteral as exc:
                if exc.args[1].startswith("Expected comma"):
                    yield self.current_token

snbt = "..."
print(RelaxedParser(nbtlib.tokenize(snbt)).parse())
```

Let me know if this can work for your use case.

**Comment by AliceDTRH** [comment]
That works wonders, I think this should be enough to figure out how to do the reverse as well! 
Thank you!
